name: SonarQube Scan

on:
  push:
    branches:
      - Workflow

jobs:
  sonarqube:
    runs-on: self-hosted

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set up Java
        uses: actions/setup-java@v2
        with:
          java-version: '11'

      - name: Analyze Code with SonarQube
        run: |
          # Install SonarScanner
          wget https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-4.6.2.2472-linux.zip
          unzip sonar-scanner-cli-4.6.2.2472-linux.zip

          # Run SonarScanner
          ./sonar-scanner-4.6.2.2472-linux/bin/sonar-scanner -Dsonar.login=$SONARQUBE_TOKEN -Dsonar.host.url=$SONARQUBE_SERVER_URL
        env:
          SONARQUBE_TOKEN: ${{ secrets.SONARQUBE_TOKEN }}
          SONARQUBE_SERVER_URL: ${{ secrets.SONARQUBE_SERVER_URL }}
